### ISSUE TITLE
Platform support

### ISSUE THREAD

**Issue by pjmagee** [julianvschijndel/net-discord-rpc#2]
Hi, 

Do you know if this would also happen to run on a Mac with .NET 5 or does the underlying implementation use something specific to the Windows OS?

**Comment by julianvschijndel** [comment]
Hi,

I don't have an Mac, so I've never tested it. Maybe if u can test it and let me work. If it does not run on Mac then let me know, so I can fix it.

**Comment by pjmagee** [comment]
> Hi,
> 
> I don't have an Mac, so I've never tested it. Maybe if u can test it and let me work. If it does not run on Mac then let me know, so I can fix it.

I was just looking through the source code, it appears that it *should* work on a Mac. I also dont have a Mac but I'm planning on making an App that runs on Windows and Mac with MAUI and am looking to use this Library. 

I think I will close the issue, because after looking at the named pipe implementation, it seems to show that Mac is supported.
